version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assign2-php
    working_dir: /var/www/html
    restart: always
    env_file:
      - ./deploy/app.env      # opsional, kalau kamu pakai file env
    volumes:
      - ./:/var/www/html      # mount code dari host
    networks:
      - app-net
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    container_name: assign2-nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8081:80"             # akses: http://localhost:8081/
    volumes:
      - ./:/var/www/html:ro   # untuk serve file statis
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net

  mysql:
    image: mysql:8.0
    container_name: assign2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: online_course
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:

volumes:
  mysql_data:

